dist: bionic
language: python

env:
  global:
    - TEST_TYPE="stable"

matrix:
  fast_finish: true
  include:
  - python: 3.5
    env: PANDAS=0.21 NUMPY=1.13
  - python: 3.5
    env: PANDAS=0.22 NUMPY=1.13
  - python: 3.6
    env: PANDAS=0.23 NUMPY=1.14
  - python: 3.7
    env: PANDAS=0.25 NUMPY=1.17 DOCBUILD=true
  - python: 3.7
    env: PANDAS=0.25 NUMPY=1.17
  - python: 3.8
    env: PANDAS=0.25 NUMPY=1.18
    # In allow failures
  - python: 3.7
    env: PANDAS="MASTER" NUMPY=1.17
  allow_failures:
    - python: 3.7
      env: PANDAS="MASTER" NUMPY=1.17

install:
  - source ci/pypi-installer.sh;
  - pip list
  - python setup.py install

script:
  - if [[ -n "${TEST_TYPE+x}" ]]; then export MARKERS="-m ${TEST_TYPE}"; fi
  - pytest -v -s -r xX "${MARKERS}" --cov-config .coveragerc --cov=runpandas --cov-report xml:/tmp/cov-runpandas.xml --junitxml=/tmp/runpandas.xml
  - |
    if (( $(echo "$TRAVIS_PYTHON_VERSION > 3.5" | bc -l) )); then
      black --check runpandas
    fi
  - flake8 --version
  - flake8 runpandas
  - |
    if [[ "$DOCBUILD" ]]; then
      set -e
      cd docs
      make html
      cd ..
      if [[ -z "$TRAVIS_TAG" ]]; then
        doctr deploy devel --build-tags
      else
        doctr deploy . --build-tags
      fi
      set +e
    fi

after_script:
  - coveralls
  - codecov