name: Upload Package to Conda
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release pyconll
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Setup Python 3.6.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - name: Install conda dependencies
        run: |
          conda install conda-build
          conda install conda-verify
          conda install anaconda-client
      - name: Build and upload conda package
        run: |
          conda build --token ${{ secrets.CONDA_API_TOKEN }} --user marcelcaraciolo -c conda-forge conda/